### ISSUE TITLE
Can't get this to work on Fedora 32

### ISSUE THREAD

**Issue by mbbroberg** [AlienKevin/Emojis-AutoKey#1]
Hey @AlienKevin, I'd love your feedback on this situation: https://github.com/autokey/autokey/issues/424

Hoping to get this going on F32 and I'd appreciate any tips on how you get it to work!

**Comment by AlienKevin** [comment]
Hello, I'm not maintaining this project personally. However, all PRs are welcome! If you are interested in maintaining this project for longer terms, I'm happy to add you as a maintainer.

**Comment by mbbroberg** [comment]
Thanks @AlienKevin, no worries. I fiddled with this for a few weeks and didn't see a path to fixing it, so I moved on to a tool that's sufficient for now. Closing this, and happy new year!
